### ISSUE TITLE
bs4 not installing 

### ISSUE THREAD

**Issue by KipCrossing** [KipCrossing/Aus-Bills#13]
```
Traceback (most recent call last):
  File "update_bills_db.py", line 2, in <module>
    from ausbills.federal_parliment import all_bills, Bill
  File "/home/os/.local/lib/python3.6/site-packages/ausbills/federal_parliment.py", line 1, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
```

**Comment by KipCrossing** [comment]
Check pip install

**Comment by connorhsm** [comment]
I think this issue is irrelevant and likely related to the bs4 package not being installed in the venv. Something like [this](https://stackoverflow.com/questions/11783875/importerror-no-module-named-bs4-beautifulsoup).

**Comment by KipCrossing** [comment]
Ok, great. Must have been just that one time. Good to close
